### ISSUE TITLE
Is there a delete uploaded file option?

### ISSUE THREAD

**Issue by erreip** [chriskuehl/fluffy#12]
I uploaded file. I copy the URL. I can share said URL and anyone has access to the uploaded file. What do I do if I want to delete this file?

Thanks,

**Comment by chriskuehl** [comment]
Unfortunately it's not possible to delete files (without being the person running the instance, anyway, and they would need to do it manually by deleting files).

One of the main principles behind fluffy's architecture is that the server doesn't keep track of uploaded files. Instead, it just hands off new uploads to one of several backends to be stored. This is useful because it adds a bunch of flexibility and keeps the code simple. But it does make some features, like deleting files, difficult to implement.

It might be interesting to add such a feature, though. I can see where it would be helpful. I think the best way to do it would be:

* Add a delete method to all the backends (potentially some might not support it, but I think all the current ones can).
* When a user uploads a file, give them a one-time URL to delete the file that must be saved. The URL can include an HMAC of the file name and a delete key.

This way it can support file deletions without adding additional infrastructure (accounts or a database). I think imgur does something similar (deletion link) for images not linked to an account.

Would something like this achieve what you want? Any thoughts?

**Comment by erreip** [comment]
>When a user uploads a file, give them a one-time URL to delete the file that must be saved. The URL can include an HMAC of the file name and a delete key.


YES! I have seen that functionality on similar services. It seems effective, though, I have no point of reference from the technical needs of implementing that.

>Would something like this achieve what you want? Any thoughts?


I believe it would be most helpful!

**Comment by chriskuehl** [comment]
I think we probably won't implement this given the current design of the app. It's a lot of extra complexity.
