### ISSUE TITLE
pasting source code with filesystem file store causes 500 error

### ISSUE THREAD

**Issue by gnowxilef** [chriskuehl/fluffy#34]
i forget if there is a workaround for this.

if pasting source code using the filesystem backend (instead of s3) and "Guess the language for me" is selected, the server throws a 500.

**Comment by chriskuehl** [comment]
@gnowxilef hmm, it's working for me. I wonder if maybe you tried to paste more than 1MB? (that caused a 500 until just now, fixed in 1d874263aee60aa10f32a09ed8f57fc617a85453)

If it's happening even on small files, can you post the traceback? (should go to stdout or stderr depending on how you're running fluffy)

**Comment by gnowxilef** [comment]
let me update to latest and double check.

**Comment by gnowxilef** [comment]
yay, seems like all is well. :)
