### ISSUE TITLE
Uploading a file greater than the max file size is broken

### ISSUE THREAD

**Issue by Baisang** [chriskuehl/fluffy#41]
Tried to upload a file greater than max file size on my phone, fluffy popped an error up and then got stuck on this screen:

http://imgur.com/a/sBR2C

**Comment by chriskuehl** [comment]
We should probably fix this in two ways:

1. Embed the max file size into the clientside JS and reject uploads before even beginning them if we know (clientside) that they're too large.
2. Fix this state bug (reset it to back to the starting state) if somehow that check doesn't catch it and the server rejects the upload.

**Comment by chriskuehl** [comment]
The UI bug is because `cancelUpload` only works when you're still in a progress bar state: https://github.com/chriskuehl/fluffy/blob/1b83571727c42d8d3edc8379978c955ca383dba0/fluffy/static/js/home.js#L203

However, `updateProgress` typically already got us out of the progress bar state: https://github.com/chriskuehl/fluffy/blob/1b83571727c42d8d3edc8379978c955ca383dba0/fluffy/static/js/home.js#L269

**Comment by chriskuehl** [comment]
5e5b760 fixes the UI bug when the server rejects your upload, 3dde63a adds a clientside warning before you upload to the server if you're definitely going to exceed the upload limit (and tells you what that limit is).
